[project]
name = "xjfx"
version = "1.2.1"
authors = [
  { name="Justin Findlay", email="justin@findlay.space" },
]
description = "Collection of simple utility functions and classes that extend standard library functionality."
readme = "README.md"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "colorama",
]

[project.urls]
"Homepage" = "https://github.com/jfindlay/xjfx/"
"Bug Tracker" = "https://github.com/jfindlay/xjfx/issues/"

[build-system]
requires = [
    "black",
    "build",
    "isort",
    "pylint",
    "pytest",
    "pyupgrade",
    "ruff",
    "setuptools",
    "tox>=4.19",
    "types-colorama",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["xjfx"]

[tool.setuptools.package-data]
xjfx = ["py.typed"]

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "broad-exception-caught",
    "consider-using-sys-exit",
    "fixme",
    "inconsistent-return-statements",
    "logging-fstring-interpolation",
    "redefined-builtin",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-positional-arguments",
]

[tool.pylint.FORMAT]
max-line-length = 128

[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"

[tool.ruff]
line-length = 128

[tool.tox]
isolated_build = true
labels = {"analyze" = ["build", "check_type", "check_import", "check_format", "check_lint"], "edit" = ["fix_format"]}

# Environments are maximized for parallelizeability, but editing actions cannot be simultaneous
[tool.tox.env.build]
package = "wheel"
wheel_build_env = "any"

# Analyze
[tool.tox.env.check_type]
allowlist_externals = ["mypy"]
deps = ["mypy", "types-colorama"]
commands = [["mypy", "src/", "tests/"]]

[tool.tox.env.check_import]
allowlist_externals = ["isort"]
deps = ["isort"]
commands = [["isort", "--check", "src/", "tests/"]]

[tool.tox.env.check_format]
allowlist_externals = ["ruff"]
deps = ["ruff"]
commands = [["ruff", "check", "src/", "tests/"]]

[tool.tox.env.check_lint]
allowlist_externals = ["pylint"]
deps = ["pylint"]
commands = [["pylint", "src/", "tests/"]]

# Edit
[tool.tox.env.fix_format]
allowlist_externals = ["isort", "ruff"]
deps = ["isort", "ruff"]
commands = [
    ["isort", "src/", "tests/"],
    ["ruff", "format", "src/", "tests/"],
]
