import collections
import enum
import typing
from _typeshed import Incomplete as Incomplete
from dataclasses import dataclass

DEVNULL: Incomplete
STDOUT: Incomplete
PIPE: Incomplete
logger: Incomplete

class ProcStreamClassifier(enum.IntEnum):
    OUTPUT = ...
    STDOUT = ...
    STDERR = ...

@dataclass
class ProcData:
    stdout: bytes | str
    stderr: bytes | str
    retcode: int

def exec_cmd(args: list[str], input: bytes | None = None, stdout: int | None = ..., stderr: int | None = ..., cwd: str | None = None, ignore_retcode: bool = False, **kwargs) -> ProcData: ...
def get_answer(prompt: str, accept: list[str], lower: bool = True) -> bool: ...
def get_yes(prompt: str): ...
def setup_logging(level: int = ...): ...

class GrouperIncomplete(enum.Enum):
    FILL = ...
    STRICT = ...
    IGNORE = ...
    REMAINDER = ...

def grouper(i: tuple | list, n: int, incomplete: GrouperIncomplete = ..., fillvalue: typing.Any = None): ...
def thr_exec(func: collections.abc.Callable, args: list[tuple], max_workers: int | None = None): ...
